// File generated by FlutterFire CLI.
// Run `flutterfire configure` to replace with your project configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'subsaver-app',
    authDomain: 'subsaver-app.firebaseapp.com',
    storageBucket: 'subsaver-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSfF0134H1nSAoOxb_F4KY0miXKeavbI',
    appId: '1:444517766764:android:90b4ae8bb43e465c106a49',
    messagingSenderId: '444517766764',
    projectId: 'my-gods-of-war',
    storageBucket: 'my-gods-of-war.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3QdDgVp36RXkaixjhXMS06iwOPwZ428Q',
    appId: '1:444517766764:ios:5ea79b4ef8a2e3d1106a49',
    messagingSenderId: '444517766764',
    projectId: 'my-gods-of-war',
    storageBucket: 'my-gods-of-war.firebasestorage.app',
    iosClientId: '444517766764-mrs2ob172ekml1kl21bupbr9hg525n7v.apps.googleusercontent.com',
    iosBundleId: 'com.subsaver.subsaver',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'subsaver-app',
    storageBucket: 'subsaver-app.appspot.com',
    iosBundleId: 'com.subsaver.subsaver',
  );
}
